---
title: "Lab_04"
author: "izd3"
output:
  pdf_document: default
  word_document: default
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load("HomeworkObjects.RData")
```

Use only commands \& functions that are shown in the indicated chapter or prior chapters.

\newpage

## Problem #01 - Chapter 16 Exercise #02  

```{r}
# Show your work here
library(stringr)
Chopper<-seq(from=-23,to=-178,length.out=47)
Hera<-rep(TRUE,times=30)
UpperBackwards<-paste(str_sort(LETTERS,decreasing = TRUE),collapse = " ")
Lists002<-list(Chopper,Hera,UpperBackwards)
str(Lists002)

```

\newpage

## Problem #02 - Chapter 18 Exercise #04a 

```{r}
# Show your work here
Loblolly[2]
str(Loblolly[2])

```

\newpage

## Problem #03 - Chapter 18 Exercise #05a 

```{r}
# Show your work here
sub_list<-subset(x=Loblolly,Loblolly$age>0 & Loblolly$height>55)
sub_list$age
str(sub_list$age)
```


\newpage

## Problem #04 - Chapter 20 Exercise #01 

```{r}
# Show your work here
squarer<-function(x){
  return(x^2)
}

test_list<-4:12
squarer(test_list)

```