---
title: "Lab_09"
author: "izd3"
output:
  word_document: default
  pdf_document: default
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load("HomeworkObjects.RData")
```

Use only commands \& functions that are shown in the indicated chapter or prior chapters.

\newpage

## Problem #01 - Chapter 34 Exercise 1A
```{r  out.height = 300, fig.height = 6, fig.width = 8}
# Show your work here
library(scales)
library(ggplot2)
scalesGraph000+scale_fill_manual(values=c('red','white','black'),breaks = c('n','c','s'),
                                 labels=c('chips','nuts','sprinkles'),name='toppings')

```

\newpage

## Problem #02 - Chapter 35 Exercise #1A 

```{r  out.height = 300, fig.height = 4, fig.width = 6}
# Show your work here
scalesGraph002+scale_x_sqrt(name='X-Axis',breaks=c(1:10,20))


```

\newpage

## Problem #03 - Chapter 37 Exercise #1A 

```{r  out.height = 300, fig.height = 6, fig.width = 12}
# Show your work here
library(forcats)
facts<-factor(factorData001)
unclass(facts)

table(facts)


```


\newpage

## Problem #04 - Chapter 37 Exercise #5A

```{r  out.height = 300, fig.height = 4, fig.width = 6}
# Show your work here

starfact<-data.frame(fact=fct_infreq(factorData005.fact))

starfact|>
  ggplot(mapping = aes(x=fact,fill=fact))+geom_bar()

```