---
title: "Lab_10"
author: "izd3"
output:
  word_document: default
  pdf_document: default
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load("HomeworkObjects.RData")
```

Use only commands \& functions that are shown in the indicated chapter or prior chapters.


\newpage

## Problem #01 - Chapter 39 Exercise #1A 

```{r  out.height = 300, fig.height = 4, fig.width = 6}
# Show your work here
library(stringr)
senlen<-str_subset(string = sentences,pattern = 'the')
head(senlen,n=10)
length(senlen)


```

\newpage

## Problem #02 - Chapter 40 Exercise #1A 

```{r  out.height = 300, fig.height = 6, fig.width = 12}
# Show your work here
senlen<-str_subset(string = sentences,pattern='ch[aeiou]')
head(senlen,n=10)
length(senlen)


```

\newpage

## Problem #03 - Chapter 38 Exercise 2A
```{r  out.height = 300, fig.height = 8, fig.width = 12}
# Show your work here
library(lubridate)
Dates002.tib$dataData=make_date(year=Dates002.tib$A,month = Dates002.tib$B,day = Dates002.tib$C)
Dates002.tib

```


\newpage

## Problem #04 - Chapter 38 Exercise #5B

```{r  out.height = 300, fig.height = 8, fig.width = 12}
# Show your work here
library(ggplot2)
Dates006.tib$dateData=ydm(Dates006.tib$dateData)
Dates006.tib|>
  ggplot(mapping=aes(x=dateData,y=soilent,color=people))+geom_line()+facet_wrap(~people)+
  scale_x_date(breaks = make_date(year=c(1900,2000,2020)),date_labels = '%Y')

```